POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "hiiii@blahblah.com",
    "password": "Password123!"
}

###

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "paper@scissors.com",
    "password": "Password456!"
}

###
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "valid@email.com",
    "password": "Password789!"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "paper@scissors.com",
    "password": "Password456!"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "valid@email.com",
    "password": "Password789!"
}

###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "hiiii@blahblah.com",
    "password": "Password123!"
}

###

PUT http://localhost:3000/savedLocations
content-type: application/json
X-Access-Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmYwYzAxODJlZjc1ZGQ0MzgwMjA1MiIsImlhdCI6MTcxODU1MzYwNywiZXhwIjoxNzE4NjQwMDA3fQ.VPnszGIRBrYOv4O8nh435qaV8akLKEPcWX75rzG3Wdo

{
    "email": "paper@scissors.com",
    "name" : "Dublin",
    "id": 5344157,
    "coord": {
        "lat": 37.7021,
        "lon": -121.9358
    }
}


###
PUT http://localhost:3000/savedLocations
content-type: application/json

{
    "email": "valid@email.com",
    "apiId": 2643743,
    "name": "London",
    "coord": {
      "lat": 51.5085,
      "lon": -0.1257
    }
}


###

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "nicholasedwardko@gmail.com",
    "password": "Password123!"
}

### 

PUT http://localhost:3000/removeLocation
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmYwYjAwMmI1MmE4N2JkNGU0NzkwMCIsImlhdCI6MTcxODcyMzQwOCwiZXhwIjoxNzE4ODA5ODA4fQ.ZH8H0Fb5HhxxtOL7D9Hm0lQyPxiihEbwSuxiCkH6cJE


{
    "email": "nicholasedwardko@gmail.com",
    "id": 2643743
}